package Lab12;

public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        createStudentMI = new javax.swing.JMenuItem();
        createTeacherMI = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        showStudentMI = new javax.swing.JMenuItem();
        showTeacherMI = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("LyTuanAn_52000620_Lab12");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel1.setText("Lý Tuấn An, 52000620");

        jMenu1.setText("*Create User");

        createStudentMI.setText("Create Student");
        createStudentMI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createStudentMIActionPerformed(evt);
            }
        });
        jMenu1.add(createStudentMI);

        createTeacherMI.setText("Create Teacher");
        createTeacherMI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createTeacherMIActionPerformed(evt);
            }
        });
        jMenu1.add(createTeacherMI);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("*Show User");

        showStudentMI.setText("Show Student Info");
        showStudentMI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showStudentMIActionPerformed(evt);
            }
        });
        jMenu2.add(showStudentMI);
        showStudentMI.getAccessibleContext().setAccessibleDescription("");

        showTeacherMI.setText("Show Teacher Info");
        showTeacherMI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showTeacherMIActionPerformed(evt);
            }
        });
        jMenu2.add(showTeacherMI);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(87, 87, 87))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                .addGap(94, 94, 94))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void createStudentMIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createStudentMIActionPerformed
        // TODO add your handling code here:
        new StudentInfo(true).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_createStudentMIActionPerformed

    private void showStudentMIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showStudentMIActionPerformed
        // TODO add your handling code here:
        new StudentInfo(false).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_showStudentMIActionPerformed

    private void createTeacherMIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createTeacherMIActionPerformed
        // TODO add your handling code here:
        new TeacherInfo(true).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_createTeacherMIActionPerformed

    private void showTeacherMIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showTeacherMIActionPerformed
        // TODO add your handling code here:
        new TeacherInfo(false).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_showTeacherMIActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Menu().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem createStudentMI;
    private javax.swing.JMenuItem createTeacherMI;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem showStudentMI;
    private javax.swing.JMenuItem showTeacherMI;
    // End of variables declaration//GEN-END:variables
}
