/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Lab4;

/**
 *
 * @author admin
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuItem1 = new javax.swing.JMenuItem();
        menuItem2 = new javax.swing.JMenuItem();
        menuItem3 = new javax.swing.JMenuItem();
        menuItem4 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menuItem5 = new javax.swing.JMenuItem();
        menuItem6 = new javax.swing.JMenuItem();
        menuItem7 = new javax.swing.JMenuItem();
        menuItem8 = new javax.swing.JMenuItem();
        menuItem9 = new javax.swing.JMenuItem();
        menuItem10 = new javax.swing.JMenuItem();
        menuItem11 = new javax.swing.JMenuItem();
        menuItem12 = new javax.swing.JMenuItem();
        menuItem13 = new javax.swing.JMenuItem();
        menuItem14 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        menuItem15 = new javax.swing.JMenuItem();
        menuItem16 = new javax.swing.JMenuItem();
        menuItem17 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Lý Tuấn An, 52000620");

        jMenu1.setText("Creating New URLs");

        menuItem1.setText("Constructing relative URLs");
        menuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(menuItem1);

        menuItem2.setText("Constructing a URL from a String");
        menuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(menuItem2);

        menuItem3.setText("Constructing a URL from its component p1");
        menuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(menuItem3);

        menuItem4.setText("Constructing a URL from its component p2");
        menuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(menuItem4);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Splitting a URL into pieces");

        menuItem5.setText("GetAuthority");
        menuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItem5ActionPerformed(evt);
            }
        });
        jMenu2.add(menuItem5);

        menuItem6.setText("GetDefaultPort");
        menuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItem6ActionPerformed(evt);
            }
        });
        jMenu2.add(menuItem6);

        menuItem7.setText("GetPort");
        menuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItem7ActionPerformed(evt);
            }
        });
        jMenu2.add(menuItem7);

        menuItem8.setText("GetFile");
        menuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItem8ActionPerformed(evt);
            }
        });
        jMenu2.add(menuItem8);

        menuItem9.setText("GetHost");
        menuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItem9ActionPerformed(evt);
            }
        });
        jMenu2.add(menuItem9);

        menuItem10.setText("GetPath");
        menuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItem10ActionPerformed(evt);
            }
        });
        jMenu2.add(menuItem10);

        menuItem11.setText("GetProtocol");
        menuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItem11ActionPerformed(evt);
            }
        });
        jMenu2.add(menuItem11);

        menuItem12.setText("GetQuery");
        menuItem12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItem12ActionPerformed(evt);
            }
        });
        jMenu2.add(menuItem12);

        menuItem13.setText("GetRef");
        menuItem13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItem13ActionPerformed(evt);
            }
        });
        jMenu2.add(menuItem13);

        menuItem14.setText("GetUserInfor");
        menuItem14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItem14ActionPerformed(evt);
            }
        });
        jMenu2.add(menuItem14);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Retrieving Data from a URL");

        menuItem15.setText("Download a web page");
        menuItem15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItem15ActionPerformed(evt);
            }
        });
        jMenu3.add(menuItem15);

        menuItem16.setText("Download an object");
        menuItem16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItem16ActionPerformed(evt);
            }
        });
        jMenu3.add(menuItem16);

        menuItem17.setText("Are the same files?");
        menuItem17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItem17ActionPerformed(evt);
            }
        });
        jMenu3.add(menuItem17);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(86, 86, 86))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                .addGap(86, 86, 86))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void menuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItem1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new Constructing_relative_URLs().setVisible(true);
    }//GEN-LAST:event_menuItem1ActionPerformed

    private void menuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItem2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new Constructing_a_URL_from_a_String().setVisible(true);
    }//GEN-LAST:event_menuItem2ActionPerformed

    private void menuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItem3ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new Constructing_a_URL_from_its_component_p1().setVisible(true);
    }//GEN-LAST:event_menuItem3ActionPerformed

    private void menuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItem4ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new Constructing_a_URL_from_its_component_p2().setVisible(true);
    }//GEN-LAST:event_menuItem4ActionPerformed

    private void menuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItem5ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new URLs_GetAuthority().setVisible(true);
    }//GEN-LAST:event_menuItem5ActionPerformed

    private void menuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItem6ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new URLs_GetDefaultPort().setVisible(true);
    }//GEN-LAST:event_menuItem6ActionPerformed

    private void menuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItem7ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new URLs_GetPort().setVisible(true);
    }//GEN-LAST:event_menuItem7ActionPerformed

    private void menuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItem8ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new URLs_GetFile().setVisible(true);
    }//GEN-LAST:event_menuItem8ActionPerformed

    private void menuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItem9ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new URLs_GetHost().setVisible(true);
    }//GEN-LAST:event_menuItem9ActionPerformed

    private void menuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItem10ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new URLs_GetPath().setVisible(true);
    }//GEN-LAST:event_menuItem10ActionPerformed

    private void menuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItem11ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new URLs_GetProtocol().setVisible(true);
    }//GEN-LAST:event_menuItem11ActionPerformed

    private void menuItem12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItem12ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new URLs_GetQuery().setVisible(true);
    }//GEN-LAST:event_menuItem12ActionPerformed

    private void menuItem13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItem13ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new URLs_GetRef().setVisible(true);
    }//GEN-LAST:event_menuItem13ActionPerformed

    private void menuItem14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItem14ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new URLs_GetUserInfo().setVisible(true);
    }//GEN-LAST:event_menuItem14ActionPerformed

    private void menuItem15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItem15ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new Download_a_web_page().setVisible(true);
    }//GEN-LAST:event_menuItem15ActionPerformed

    private void menuItem16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItem16ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new Download_an_object().setVisible(true);
    }//GEN-LAST:event_menuItem16ActionPerformed

    private void menuItem17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItem17ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new Check_SameFile().setVisible(true);
    }//GEN-LAST:event_menuItem17ActionPerformed
    
    public static void backToMenu(javax.swing.JFrame e) {
        e.dispose();
        new Menu().setVisible(true);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Menu().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem menuItem1;
    private javax.swing.JMenuItem menuItem10;
    private javax.swing.JMenuItem menuItem11;
    private javax.swing.JMenuItem menuItem12;
    private javax.swing.JMenuItem menuItem13;
    private javax.swing.JMenuItem menuItem14;
    private javax.swing.JMenuItem menuItem15;
    private javax.swing.JMenuItem menuItem16;
    private javax.swing.JMenuItem menuItem17;
    private javax.swing.JMenuItem menuItem2;
    private javax.swing.JMenuItem menuItem3;
    private javax.swing.JMenuItem menuItem4;
    private javax.swing.JMenuItem menuItem5;
    private javax.swing.JMenuItem menuItem6;
    private javax.swing.JMenuItem menuItem7;
    private javax.swing.JMenuItem menuItem8;
    private javax.swing.JMenuItem menuItem9;
    // End of variables declaration//GEN-END:variables
}
